

POST / HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "param1": "value1",
  "param2": "value2"
}

##########################

GET /users HTTP/1.1
Host: localhost:3000
Content-Type: application/json

##########################

POST /users HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "name": "Alexei", "age": 27
}